# GETTING BASE IMAGE
FROM ubuntu

RUN apt-get update
# RUN apt-get install -y python
# RUN python --version
RUN apt-get install -y pip
RUN pip --version
RUN python3 --version
RUN apt-get install -y git
RUN git --version
# RUN pip install elastalert
# RUN mkdir elastalert
# RUN cd elastalert

CMD ["echo", "python --version, pip --version"]